version: "2.2"

networks:
  contract:

services:

  ca.verizon.com:
    image: hyperledger/fabric-ca
    container_name: ca.verizon.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.verizon.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../CA/fabric-ca/verizon:/etc/hyperledger/fabric-ca-server
    networks:
      - contract

  ca.vodafone.com:
    image: hyperledger/fabric-ca
    container_name: ca.vodafone.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.vodafone.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - 8054:8054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../CA/fabric-ca/vodafone:/etc/hyperledger/fabric-ca-server
    networks:
      - contract

  ca.airtel.com:
    image: hyperledger/fabric-ca
    container_name: ca.airtel.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.airtel.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - 9054:9054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../CA/fabric-ca/airtel:/etc/hyperledger/fabric-ca-server
    networks:
      - contract