version: "2.2"

networks:
  contract:

services:

  orderer.verizon.com:
    image: hyperledger/fabric-orderer:2.2
    container_name: orderer.verizon.com
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=VerizonOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=false
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_GENERAL_LISTENPORT=7050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
      - 8443:8443
    networks:
      - contract
    volumes:
      - ../channel/genesis.block:/var/hyperledger/orderer/genesis.block
      - ../crypto-config/ordererOrganizations/verizon.com/orderers/orderer.verizon.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/verizon.com/orderers/orderer.verizon.com/tls:/var/hyperledger/orderer/tls

  orderer.vodafone.com:
    image: hyperledger/fabric-orderer:2.2
    container_name: orderer.vodafone.com
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=VodafoneOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=false
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_GENERAL_LISTENPORT=8050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 8050:8050
      - 8444:8443
    networks:
      - contract
    volumes:
      - ../channel/genesis.block:/var/hyperledger/orderer/genesis.block
      - ../crypto-config/ordererOrganizations/vodafone.com/orderers/orderer.vodafone.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/vodafone.com/orderers/orderer.vodafone.com/tls:/var/hyperledger/orderer/tls

  orderer.airtel.com:
    image: hyperledger/fabric-orderer:2.2
    container_name: orderer.airtel.com
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=AirtelOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=false
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_GENERAL_LISTENPORT=9050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 9050:9050
      - 8445:8443
    networks:
      - contract
    volumes:
      - ../channel/genesis.block:/var/hyperledger/orderer/genesis.block
      - ../crypto-config/ordererOrganizations/airtel.com/orderers/orderer.airtel.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/airtel.com/orderers/orderer.airtel.com/tls:/var/hyperledger/orderer/tls

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - contract

  couchdb2:
    container_name: couchdb2
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    networks:
      - contract

  couchdb3:
    container_name: couchdb3
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7984:5984
    networks:
      - contract

  peer0.verizon.com:
    container_name: peer0.verizon.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_LOCALMSPID=VerizonMSP
      - CORE_PEER_ID=peer0.verizon.com
      - CORE_PEER_ADDRESS=peer0.verizon.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.verizon.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.verizon.com:8051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.verizon.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    depends_on:
      - couchdb1
    ports:
      - 7051:7051
    volumes:
      - ../crypto-config/peerOrganizations/verizon.com/peers/peer0.verizon.com/msp:/etc/hyperledger/crypto/peer/msp
      - ../crypto-config/peerOrganizations/verizon.com/peers/peer0.verizon.com/tls:/etc/hyperledger/crypto/peer/tls
      - ../channel/:/etc/hyperledger/channel/
    networks:
      - contract

  peer0.vodafone.com:
    container_name: peer0.vodafone.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_LOCALMSPID=VodafoneMSP
      - CORE_PEER_ID=peer0.vodafone.com
      - CORE_PEER_ADDRESS=peer0.vodafone.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.vodafone.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.vodafone.com:9051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.vodafone.com:10051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    depends_on:
      - couchdb2
    ports:
      - 9051:9051
    volumes:
      - ../crypto-config/peerOrganizations/vodafone.com/peers/peer0.vodafone.com/msp:/etc/hyperledger/crypto/peer/msp
      - ../crypto-config/peerOrganizations/vodafone.com/peers/peer0.vodafone.com/tls:/etc/hyperledger/crypto/peer/tls
      - ../channel/:/etc/hyperledger/channel/
      - /var/run/:/host/var/run/
    networks:
      - contract
  
  peer0.airtel.com:
    container_name: peer0.airtel.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_LOCALMSPID=AirtelMSP
      - CORE_PEER_ID=peer0.airtel.com
      - CORE_PEER_ADDRESS=peer0.airtel.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.airtel.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.airtel.com:11051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.airtel.com:12051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    depends_on:
      - couchdb3
    ports:
      - 11051:11051
    volumes:
      - ../crypto-config/peerOrganizations/airtel.com/peers/peer0.airtel.com/msp:/etc/hyperledger/crypto/peer/msp
      - ../crypto-config/peerOrganizations/airtel.com/peers/peer0.airtel.com/tls:/etc/hyperledger/crypto/peer/tls
      - ../channel/:/etc/hyperledger/channel/
    networks:
      - contract

  ca.verizon.com:
    image: hyperledger/fabric-ca
    container_name: ca.verizon.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.verizon.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../CA/fabric-ca/verizon:/etc/hyperledger/fabric-ca-server
    networks:
      - contract

  ca.vodafone.com:
    image: hyperledger/fabric-ca
    container_name: ca.vodafone.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.vodafone.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - 8054:8054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../CA/fabric-ca/vodafone:/etc/hyperledger/fabric-ca-server
    networks:
      - contract

  ca.airtel.com:
    image: hyperledger/fabric-ca
    container_name: ca.airtel.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.airtel.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - 9054:9054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../CA/fabric-ca/airtel:/etc/hyperledger/fabric-ca-server
    networks:
      - contract